services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/testcom:cached
      - ./xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
    ports:
      - "80:80"
      - "443:443"
      - "3306:3306"
      - "6080:6080"
    command: sleep infinity

  mysql:
    image: mysql:8.0
    profiles: ["mysql", "default"]
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_joomla
      MYSQL_USER: joomla_ut
      MYSQL_PASSWORD: joomla_ut
    volumes:
      - "mysql-data:/var/lib/mysql"

  db_pgsql:
    image: postgres:16
    profiles: ["pgsql"]
    restart: unless-stopped
    environment:
      POSTGRES_DB: test_joomla
      POSTGRES_USER: joomla_ut
      POSTGRES_PASSWORD: joomla_ut
    volumes:
      - db_pgsql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "8025:8025"
volumes:
  mysql-data:
  db_pgsql_data:
